### ISSUE TITLE
Fails in Chrome 57 due to sendBeacon()

### ISSUE THREAD

**Issue by SoulAuctioneer** [GoogleCloudPlatform/stackdriver-errors-js#10]
It looks like sendBeacon() cannot be used with the ContentType "application/json; charset=UTF-8"

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
> The only allowed values for the Content-Type header are:
> application/x-www-form-urlencoded
> multipart/form-data
> text/plain

More info at http://crbug.com/490015

Full error:
```
Uncaught (in promise) DOMException: Failed to execute 'sendBeacon' on 'Navigator': sendBeacon() with a Blob whose type is not CORS-safelisted MIME type is disallowed experimentally. See http://crbug.com/490015 for details.
    at n.sendErrorPayload (https://cdn.rawgit.com/GoogleCloudPlatform/stackdriver-errors-js/v0.0.5/dist/stackdriver-errors-concat.min.js:2:16470)
    at https://cdn.rawgit.com/GoogleCloudPlatform/stackdriver-errors-js/v0.0.5/dist/stackdriver-errors-concat.min.js:2:16135
```

**Comment by steren** [comment]
Thanks for the report. 

`sendBeacon()` was introduced in https://github.com/GoogleCloudPlatform/stackdriver-errors-js/pull/8 and published in v0.0.5 of this lib.

For now and until we fix the problem, you can use v0.0.4 that is not using this API. I am going to update the README of the repo.

@tinovyatkin are you available to work on a fix for the `sendBeacon()` change?

**Comment by tinovyatkin** [comment]
Hi!
`MIME type is disallowed experimentally` that something fantastic to fix... Will check for workaround for this experiment

**Comment by tinovyatkin** [comment]
Chrome developers seems to decided to throw on any Blob with non simple content-type and collect telemetry to understand how it can affect. Seems weird decision for me, but at this point I'm the easiest workaround it rollback to non-beacon version, unfortunately.
