### ISSUE TITLE
What happens when I create 2 reporter instances?

### ISSUE THREAD

**Issue by ZYinMD** [GoogleCloudPlatform/stackdriver-errors-js#101]
Quick question: If I initiate two reporter instances, will uncaught errors be sent twice?

Here's my setup (may not be important info for answering the question, but just in case): My app has a main window and an embedded iframe which is another site. I installed this package in the main window. I can't install it in the iframe site, but I can use postMessage to pass caught errors to the main site, then reported them. I want to initiate 2 separate instances in order to have different service name and version numbers, but I wonder what will happen to uncaught errors in the main window.

**Comment by steren** [comment]
Good question. You should try and report here.

**Comment by ZYinMD** [comment]
Ok I've tested, the result is it will report twice.

So, the best practice will be set `reportUncaughtExceptions` and `reportUnhandledPromiseRejections` to true on one, false on the other one.
