### ISSUE TITLE
Integration with ReactJs?

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/stackdriver-errors-js#11]
Anyone have a how-to or can direct me on how to get going with this?  Outside of adding the scripts to the bottom of the the root `index` file?

Going to give this a whirl over the next few days but would love to see any insight.

**Comment by steren** [comment]
I do not have first hand experience with React, if you know this framework, feel free to send a PR with React setup documentation in the README.

**Comment by oshalygin** [comment]
@steren will do! Going to take a look this weekend.

**Comment by oshalygin** [comment]
Resolved as part of #12
