### ISSUE TITLE
Where do you see user in error reporting?

### ISSUE THREAD

**Issue by ElixirMike** [GoogleCloudPlatform/stackdriver-errors-js#110]
If I set the user context , is there a way to see this in the Google Error Reporting console?? I've defined it, but I don't see a way to add/show this data in the console itself.

```
 errorHandler.start({
 ....
    context: {user: 'User1'}
  });
```

**Comment by TriPSs** [comment]
If you open the error in error reporting you will see it here:
![image](https://user-images.githubusercontent.com/7668692/143472470-6c43817d-4b37-47bf-a291-0b38b44086a6.png)

Also, if you open it in the logs it will be here:
![image](https://user-images.githubusercontent.com/7668692/143472605-d6e278c5-6c4f-4b2f-94cf-ea816f19644e.png)

**Comment by steren** [comment]
Thanks @TriPSs
