### ISSUE TITLE
Log Severity

### ISSUE THREAD

**Issue by adamsuskin** [GoogleCloudPlatform/stackdriver-errors-js#121]
Hello! Is there a way to configure the severity of the logs that get sent to GCP?

**Comment by steren** [comment]
This question is out of scope of this Error Reporting module

**Comment by adamsuskin** [comment]
@steren is there a Warning and/or Info Reporting module? 😂

Jokes aside, I'm mainly asking to what extent y'all have thought about this. If the answer is "none, and I don't want to" I'll take it. Just didn't want to assume that if y'all had put in work that I was somehow unable to find.
