### ISSUE TITLE
Open to writing the application code in ES6 with a Babel transpilation step?

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/stackdriver-errors-js#13]
@steren , would this project be open to having the source code written in ES6 and then transpiled down to ES5 via Babel?  The `build` command would perform this and as part of any release the `npm` the entry-point would reference the minified/transpiled code?

**Comment by steren** [comment]
I have nothing against the idea, if it brings a clear value.

Keep in mind that currently, this library is [~100 lines](https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/stackdriver-errors.js). The simplest we keep it, the better.

So before moving to ES6, I'd like to understand what it will bring in term of developer velocity or in term of library usability.

**Comment by steren** [comment]
After further thinking, I think we should keep things simple and stick with vanilla JS
