### ISSUE TITLE
Preventing StackTrace is not defined on browser when using Browserify

### ISSUE THREAD

**Issue by willycamargo** [GoogleCloudPlatform/stackdriver-errors-js#15]
I'm trying to use this lib with Browserify + ES6 syntax.

```js
import { StackdriverErrorReporter } from 'stackdriver-errors-js'
```

But, when I try to test it with some error I receive this:

```
Uncaught ReferenceError: StackTrace is not defined at StackdriverErrorReporter.report
```

![image](https://user-images.githubusercontent.com/5041887/26847594-019e9b08-4ad4-11e7-8ac7-c6aef95b312a.png)

[Error line](https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/stackdriver-errors.js#L107)

Everything works fine when I use self-hosted CDN.

**Comment by ties** [comment]
After adding `stacktrace-js` as an dependency to package.json and adding the following line to my entrypoint it worked for me:
```
window.StackTrace = require('stacktrace-js');
```

**Comment by steren** [comment]
I am not an ES6 expert, but indeed, if only stacjdriver-errors.js is loaded, it assumes that stacktrace.js has been loaded previously.

Any help improving the ES6 module architecture is welcome: https://github.com/GoogleCloudPlatform/stackdriver-errors-js/issues/2

As well as suggesting edits to the setup instructions in the README,

**Comment by willycamargo** [comment]
`stacktrace-js` is a dependency of the `stackdriver-errors-js`. So I think that it should be imported into it.

It is listed on [this project dependencies](https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/package.json#L37). I think that the solution is add a `var StackTrace = require('stacktrace-js');` on `stackdriver-errors.js` file.

**Comment by steren** [comment]
But that would assume we use ES6. Which, as explained in https://github.com/GoogleCloudPlatform/stackdriver-errors-js/issues/13, I am not sure it's worth the effort.

**Comment by willycamargo** [comment]
Hmm. I got it.
You're right!

But installing the module with npm will cause this error on any app, since that `node_modules` normally isn't present on Client Apps when it is deployed to production.

Normallly packages installed by npm are used with AMD, CommonJS, etc. (using ES6 or no)

So the solution is provide the JS module architecture, as mentioned in #2

I guess I can do it in my free time.
