### ISSUE TITLE
Question: Security Concern of Exposing GCP Project ID And API Key .

### ISSUE THREAD

**Issue by shinofara** [GoogleCloudPlatform/stackdriver-errors-js#16]
Would not it be possible to issue a salt for each project instead of using Project ID and API KEY raw, so that it can be reversibly encrypted and used?

There is no problem assuming that API keys are used and beaten unnecessarily

**Comment by steren** [comment]
The security concerns have been answered in https://github.com/GoogleCloudPlatform/stackdriver-errors-js/issues/9
