### ISSUE TITLE
StackTrace is not defined

### ISSUE THREAD

**Issue by mbeauchamp7** [GoogleCloudPlatform/stackdriver-errors-js#19]
![image](https://user-images.githubusercontent.com/15185355/30566279-cc7d1704-9ca1-11e7-96c9-e203f4858845.png)

I tried to quickly connect and test and got this error. I'm using webpack/react and used it like this.
```
var StackdriverErrorReporter = require("stackdriver-errors-js").StackdriverErrorReporter;

export function initErrorLogging() {
  const errorHandler = new StackdriverErrorReporter();
  errorHandler.start({
    key: STACKDRIVER_API_KEY,
    projectId: GCP_PROJECT_ID,
    //service: '<my-service>',              // (optional)
    //version: '<my-service-version>'       // (optional)
  });
}
```

I suppose you could include StackTrace as a dependency.

**Comment by steren** [comment]
If you load the `stackdriver-errors.js`file, this one assumes that the `stacktrace-js` module has been loaded.

I never tested this module with webpack. Feel free to add more install details to the [README](https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/README.md) and send fixes.

**Comment by mbeauchamp7** [comment]
I never worked with the gulp workflow so I don't really how to get this working properly :(

**Comment by steren** [comment]
Does importing the `stacktrace-js` module solve the issue?

**Comment by mbeauchamp7** [comment]
I haven't tried sorry.. I didn't know stackdriver had it's own api so I'll just write a few lines to report the errors. Thanks anyways!

**Comment by steren** [comment]
As you want. But technically, those few lines will be https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/stackdriver-errors.js

**Comment by whitecolor** [comment]
@steren How this stacktrace-js should be imported?

```
require('stacktrace-js')
const { StackdriverErrorReporter } = require('stackdriver-errors-js')

window.addEventListener('DOMContentLoaded', function () {
  console.warn('Error reporting on')
  window.errorHandler = new StackdriverErrorReporter();
  window..errorHandler.start({
  
  })
})
```

gives an error:
![image](https://user-images.githubusercontent.com/736697/42278822-639f911a-7fb5-11e8-8a43-64c500bce3ad.png)

**Comment by steren** [comment]
When you do `require('stacktrace-js')`, does it exposes a global `StackTrace` object?
This is what is expected by `stackdriver-errors.js`
