### ISSUE TITLE
Error message not sent when reporting from Chrome's console.

### ISSUE THREAD

**Issue by ubershmekel** [GoogleCloudPlatform/stackdriver-errors-js#21]
The example string error report: `errorHandler.report('Something broke!');` causes this:

```
{
  "error": {
    "code": 400,
    "message": "ReportedErrorEvent.context must contain a location unless `message` contain an exception or stacktrace.",
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by steren** [comment]
I can indeed reproduce, but only when I try in Chrome DevTools' console. Can you confirm this is where you are trying the command?

When I use the library from a .js file, the error is properly sent.

**Comment by steren** [comment]
We could even think that this is working as intended: in Chrome's console, there is no stack trace, thus Stackdriver Error Reporting is unable to group the error.

**Comment by ubershmekel** [comment]
I can confirm I used the chrome dev tools console. But I also added my own `throw new Error('bla')` in my code which did not register in the dashboard.

The only thing that landed in the stack driver dashboard was this example `(function testErrorReporting() {window.onerror(null, null, null, null, new Error('Test: Something broke!'));})();`

I think Chrome's console has a stack trace:

```
(new Error('in the console')).stack
"Error: in the console
    at <anonymous>:1:2"
```

E.g. you can imagine a website that requires console interactions - it should be able to send errors with the console at the top of the stack.

**Comment by steren** [comment]
Where do you do `throw new Error('bla')`, what is it's stacktrace?

Once again, if it's empty, or 'anonymous', Error Reporting will not be able to group it.

**Comment by ubershmekel** [comment]
Looked a bit harder at the console and saw you guys were throwing:

>Uncaught TypeError: Cannot read property 'message' of null
> if (typeof errorObject !== 'undefined' && typeof errorObject.message !== 'undefined') {

If I had to guess - someone's IDE made a squiggly under `!errorObject` because it's an undeclared variable and this is the fix...

**Comment by ubershmekel** [comment]
Actually - that's not your code and it's intercepting the error. Sorry for the goose chase. I removed the intercepting code and still am getting no reports of a `throw new Error` in my code. I saved the error to a global variable to inspect it.

```
>window.mye.stack
"Error: testing the error reporting
    at my.main (https://cdn.shopify.com/s/files/1/1805/2745/t/1/assets/1-shopify.js?7001019835927764811:205:13)
    at defer (https://cdn.shopify.com/s/files/1/1805/2745/t/1/assets/1-shopify.js?7001019835927764811:216:9)
    at https://cdn.shopify.com/s/files/1/1805/2745/t/1/assets/1-shopify.js?7001019835927764811:222:1"
```

**Comment by steren** [comment]
Thanks for the investigating, but I'm still confused by what is the problem.

The best would be for you to reproduce the problem, write a test for it, and propose a fix. The code is very straightforward: 

- code: https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/stackdriver-errors.js
- tests: https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/test/test.js

**Comment by ubershmekel** [comment]
It seems some errors get reported and some don't. I've also noticed that if I have errors during initial page load they do not show up on the console unless I remove the stackdriver-errors-js snippet.

I'm not sure when I'll have time to create a small repro repo. But if you're curious before that time I've left a thrown error at: https://shop.rylo.com so you can open the console there and see `fyi stackdriver error` through a `console.log`. Note that error is not being reported in Chrome though looking now at the reports it seems it is being reported on firefox.

**Comment by Jastrzebowski** [comment]
I've dug a bit into it, and manage to fix the format by adding `<anonymous>` if there is no `functionName` — scope is an anonymous function, global or console, full info in PR

**Comment by ubershmekel** [comment]
I've disabled the error throwing for now, assuming @Jastrzebowski got it for now. Waiting for the next release to retest.

**Comment by steren** [comment]
I created a new release, which should fix this issue.
