### ISSUE TITLE
Has an undocumented dependency on StackTrace

### ISSUE THREAD

**Issue by achew22** [GoogleCloudPlatform/stackdriver-errors-js#22]
It took me a while to figure out that the project depended on https://www.stacktracejs.com/

**Comment by steren** [comment]
Undocumented? https://github.com/GoogleCloudPlatform/stackdriver-errors-js/blob/master/package.json#L37

**Comment by achew22** [comment]
I couldn't add the .min.js since it redefined my module system so I was trying to reconstruct things manually.
