### ISSUE TITLE
Count sessions on Stack Driver Error Reporting?

### ISSUE THREAD

**Issue by ubershmekel** [GoogleCloudPlatform/stackdriver-errors-js#28]
It would be nice if there was a way to see "percentage of sessions with errors" on the error reporting dashboard. Having 20 errors per day is horrible if you had 20 sessions, but it's nothing to worry about if you had 200,000 sessions.

**Comment by steren** [comment]
You can achieve that by using the `context.user` field (see the [README](https://github.com/GoogleCloudPlatform/stackdriver-errors-js))

The UI will then display a user count as a column in the Error list view.

**Comment by steren** [comment]
If you do not have a user ID, you could imagine generating one and storing it in localstorage.

**Comment by ubershmekel** [comment]
@steren per this advice, I've introduced a uuid user id saved in localStorage. The dashboard now tells me how many users are affected by a bug. It doesn't tell me the percentage of total users affected. I.e. I look at my dashboard knowing how many users are impacted - but not if the sky is falling vs a minor glitch in the matrix.

**Comment by ubershmekel** [comment]
To clarify - I think it would be nice if stackdriver reported and tracked NON-ERROR sessions.

**Comment by steren** [comment]
This is a great feature request for the Stackdriver Error Reporting product itself. I will pass the feedback.
