### ISSUE TITLE
Send logs that aren't errors

### ISSUE THREAD

**Issue by gillyb** [GoogleCloudPlatform/stackdriver-errors-js#37]
Can this turn into a more 'general' logging solution for websites to send logs from the client?
I would like to have the ability to send metric based logs from my web app, and also log messages that aren't specifically errors.
(I will write the functionality myself if there's a chance it will be accepted)

**Comment by steren** [comment]
No, this library will not be transformed into a general client-side logging solution. It's purpose is to capture application errors only.

**Comment by gillyb** [comment]
@Jastrzebowski yep i think so too. But I took another look at the stackdriver capabilities, and it doesn't contain a general client side logging option - it's originally only intended for errors, so if developed, it will have to be over another platform.
