### ISSUE TITLE
CDNs

### ISSUE THREAD

**Issue by Jastrzebowski** [GoogleCloudPlatform/stackdriver-errors-js#38]
Rawgit is fine for examples but imo for a production setup would be nice to have a CDN published version. Should we use Google, or an external one like cdnjs.com?

**Comment by steren** [comment]
For a production setup, I recommend serving the library from the same place where your other JS files are served.

Do you think we'd better use cdnjs.com in the README compared to rawgit. According to https://rawgit.com, cdn.rawgit.com is suited for production use.

**Comment by Jastrzebowski** [comment]
Rawgit is ok in the documentation, I never tried it in production setup though. As lib is self-sustainable it can be safely deployed and used from a CDN so having more options is always good, cdnjs is probably the best known public CDN I would start with it.

**Comment by steren** [comment]
Serving from cdn.rawgit.com is suited for production, this is what https://rawgit.com says.
