### ISSUE TITLE
Cross origin error while send

### ISSUE THREAD

**Issue by whitecolor** [GoogleCloudPlatform/stackdriver-errors-js#44]
I've got this error in browser when try to use `report` method:

> Access to XMLHttpRequest at 'webpack:///node_modules/stackdriver-errors-js/stackdriver-errors.js' from origin 'https://mysite.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

I init error reporter using such code:
```ts
  window.StackTrace = require('stacktrace-js')
  window.StackTrace.get({ offline: true })
  const { StackdriverErrorReporter } = require('stackdriver-errors-js')

  window.addEventListener('DOMContentLoaded', function () {
    window.errorHandler = new StackdriverErrorReporter()
    window.errorHandler.start({
      key: apiKey,
      projectId: 'my-projectid',
      reportUncaughtExceptions: isProduction,
      service: 'serviceName',
      version: buildNo
    })    
    if (process.env.NODE_ENV === 'development') {
      window.errorHandler.setUser('dev')
    }
  })
```

**Comment by whitecolor** [comment]
On the website build with Webpack. Ah it still sends the message despite the error shown (which is shown only on the frist report call).

So I believe may close this. Thanks)

**Comment by jesusvallez** [comment]
Sorry for reopen this issue but I have the same problem. 
When some error is throw through npm library in my dev machine, I got this cors error.

> Access to XMLHttpRequest at 'webpack:///node_modules/stackdriver-errors-js/stackdriver-errors.js' from origin 'https://mysite.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

@wclr Did you fix the problem?

**Comment by steren** [comment]
the fact that the request originates from `webpack:///` is most likely the issue. I have no idea why the JS file is served from a non https protocol. Webpack seems the be the culprit here.

**Comment by vedang-telus** [comment]
Hi @jesusvallez @wclr , I know this issue is closed, but have we ever found a solution to this? I am implementing it with reactJS and nextJS and received same error. Thanks!!

**Comment by Almoglem** [comment]
@vedang-telus @jesusvallez Hey, did you end up finding a solution to this? I'm encountering the exact same issue, also with react & next

**Comment by jesusvallez** [comment]
unfortunately we have not found anything, sorry
