### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/stackdriver-errors-js#7]
Bower does not seem to be a thing anymore. But developers expect to install client-side dependencies via npm.

We should provide an npm module.

**Comment by oshalygin** [comment]
This is fairly straightforward to accomplish, any concerns?

**Comment by steren** [comment]
Hi,
Indeed it is straightforward. I think I initially waited for the library to stabilize.
I'll do it within a week.

**Comment by oshalygin** [comment]
thanks @steren , would love to contribute in the coming weeks as well.

**Comment by steren** [comment]
I pushed the latest version to npm: https://www.npmjs.com/package/stackdriver-errors-js

I will now update the README to mention it.

**Comment by oshalygin** [comment]
Awesome thanks @steren !!! Sorry been a bit mia on some items, work has gotten hectic.  Thanks for pushing this!!
