### ISSUE TITLE
ETA for the next release

### ISSUE THREAD

**Issue by marcosinger** [GoogleCloudPlatform/stackdriver-errors-js#74]
Hi there,

First, thanks for creating this library. I'd like to know if there is any plan to release a new version with [support for custom function for reporting error](https://github.com/GoogleCloudPlatform/stackdriver-errors-js/commit/5b1898a31f40c30c96f0fdfa55232294011cc6c6) soon.

I'm working on an environment in which `git` is not enabled by default, so I need to rely on `npm` versions.

Thanks in advance!

**Comment by steren** [comment]
Sorry for missing cutting a release, I'll do it this week

**Comment by steren** [comment]
0.8.0 should be on NPM now
