### ISSUE TITLE
Question: Security Concern of Exposing GCP API Key

### ISSUE THREAD

**Issue by touhonoob** [GoogleCloudPlatform/stackdriver-errors-js#9]
Is there a way to securely expose GCP API key to public?
There doesn't seem to be an option to limit service access on the level of per API key.

**Comment by steren** [comment]
This is a valid concern. And I asked the question explicitly to the Cloud API team.

You are correct: at the moment, developers cannot restrict the APIs or permissions that can be used with a given API key.
In a client, there is no way to hide a secret. So there is no other mechanism that can be used than API key.
By using the API key that can be found in the client, a user can call any API of the Cloud project that accepts API keys (most of the Cloud APIs don't). 
To counter this, you cab create a dedicated Cloud project to use to collect errors only.

I recommend reading these [Best practices](https://support.google.com/cloud/answer/6310037), in particular, you **should restrict the referrer URL of your API to the website from which you intend to report errors**.

**Comment by jer-tx** [comment]
This is a fairly old, have there been any changes about this? Creating a whole separate project just for logging is very cumbersome for those of us that have multiple kinds of applications (Python and JS) to have to switch back and forth just to get logging information. Are there any better solutions?

**Comment by touhonoob** [comment]
@jer-tx The issue has been resolved by https://cloud.google.com/docs/authentication/api-keys?#api_key_restrictions
