### ISSUE TITLE
New release to NPM?  Current one is a year old.

### ISSUE THREAD

**Issue by cakoose** [GoogleCloudPlatform/stackdriver-errors-js#95]
The current package version on NPM is 0.8.0, released Feb 2020.  There have been a few improvements to the library since then.  Would be nice to have a new release on NPM.

**Comment by steren** [comment]
I am currently unable to generate a new version due to https://github.com/GoogleCloudPlatform/stackdriver-errors-js/issues/91

Help is appreciated on fixing this issue

**Comment by xlfe** [comment]
> I am currently unable to generate a new version due to #91
> 
> Help is appreciated on fixing this issue

See #94

**Comment by steren** [comment]
0.10.0 has been published
