### ISSUE TITLE
package installed via npm doesnt have type definition

### ISSUE THREAD

**Issue by mohamedfasil** [GoogleCloudPlatform/stackdriver-errors-js#97]
Hi typings is missing when we install via npm 
```
npm install stackdriver-errors-js

```
![Screenshot 2021-08-24 at 5 59 41 PM](https://user-images.githubusercontent.com/529158/130616531-25945444-0ad0-408d-9b23-cbb3bb737f00.png)

**Comment by casparolesen** [comment]
@steren Any chance we can get a new release with the renamed definition file? 😄

**Comment by steren** [comment]
I'm pushing to npm now

**Comment by casparolesen** [comment]
> I'm pushing to npm now

It seems that the definition file isn't included in the npm package? This is the contents of the folder on 0.11.0:

![image](https://user-images.githubusercontent.com/17333455/136554129-38ec1634-7991-4f59-b1e0-e3999db9cae0.png)

**Comment by steren** [comment]
Tracked at https://github.com/GoogleCloudPlatform/stackdriver-errors-js/issues/100
